### ISSUE TITLE
Issue: Date corruption (ruTorrent Interface)

### ISSUE THREAD

**Issue by vincegre** [SpaceK33z/movieo-to-plex#170]
<details>
<summary>Original</summary>
When Web to Plex extension is active in my Firefox on Linux it messes all dates indicated in the web interface of rutorrent that I use for my seedbox ! If I deactivate Web to Plex extension, everything is back to normal !
</details>

----

> When using Web to Plex and ruTorrent, the web interface (dates) is distorted. Does not occur when the extension is uninstalled

**To Reproduce**
1. Install Web to Plex
2. Access the ruTorrent web interface

**Expected behavior**
No interaction between Web to Plex and ruTorrent's web interface

**Extension Information**
 - Version: `3.4`
 - Source: `store`
 - Browser: `firefox`
 - Operating System: `Ubuntu 18.04.4 LTS`

**Comment by Ephellon** [comment]
Update to [`v4.1.2.4`](https://github.com/SpaceK33z/web-to-plex/releases/tag/v4.1.2.4-1900MST19FEB2020)

**Comment by Ephellon** [comment]
Assuming issue has been resolved. Please re-open if you experience the same problem

**Comment by vincegre** [comment]
Nope sorry I didn't get the notification of your answer but problem is still present ! I have deactivated for now the Web to Plex plugin to avoid the problem !

**Comment by Ephellon** [comment]
OK, could you enable `Developer mode` in the settings and set the shape to `box`?

**Comment by vincegre** [comment]
> OK, could you enable `Developer mode` in the settings and set the shape to `box`?

In the plugin ? as I find nothing or in FF ?

**Comment by Ephellon** [comment]
# The extension &rarr;

> Enabling `Developer mode` &mdash; `Settings` &rarr; `Advanced Settings` &rarr; `Developer Options`
>
> ![image](https://user-images.githubusercontent.com/8632548/80895642-43e7a080-8ca4-11ea-8f45-e724435c773a.png)

> Setting the shape to box &mdash; `Settings` &rarr; `Theme Settings` &rarr; `The Master (Main) Button`
>
> ![image](https://user-images.githubusercontent.com/8632548/80895665-801b0100-8ca4-11ea-8a74-820dd040cbec.png)

**Comment by vincegre** [comment]
Thanks for the explanation that made me realise that version I have installed from FF store is very outdated (version 3) but link to download version 4 for FF on github gives 404 and if I try to find the plugin on FF store I find only the version 3 :( way to get it installed by hand ?

**Comment by Ephellon** [comment]
Yes, please use the `ZIP` or `XPI` found in the Wiki, README, or Source files

**Comment by Ephellon** [comment]
*Mozilla has disabled v4.1* &rarr; #167
